[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config