name: "Workflow for Contract Feature branches"

on:
  push:
    branches-ignore:
      - main

jobs:
  compile:
    name: NPM compile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: NPM compile
        run: |
          npm install
          npm run compile

  test:
    needs: [compile]
    name: NPM test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: NPM test
        run: |
          npm install
          npm run test

  lint:
    needs: [compile]
    name: NPM lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: NPM lint
        run: |
          npm install
          npm run lint

  analyze:
    name: Slither Analysis
    needs: [compile]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: |
          forge install
          npm install

      - name: Build project
        run: forge build --build-info --force

      - uses: crytic/slither-action@v0.4.0
        id: slither
        with:
          ignore-compile: true
          target: "src/"
          sarif: results.sarif
          fail-on: none

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
