name: "Workflow for Contract Feature branches"

on:
  push:
    branches-ignore:
      - main

jobs:
  compile:
    name: NPM compile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: NPM compile
        run: |
          npm install
          npm run compile

  test:
    needs: [compile]
    name: NPM test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: NPM test
        run: |
          npm install
          npm run test

  solhint:
    needs: [compile]
    name: Solhint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install solhint
        run: |
          npm install -g solhint
          solhint --version

      - name: Initialize solhit
        run: solhint --init

      - name: Run solhint
        run: solhint 'src/**/*.sol'

  analyze:
    name: Slither Analysis
    needs: [compile]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          target: "src/"
          sarif: results.sarif
          fail-on: none

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
